/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-10-31 06:19:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"javaScript/studentValidation.js\"></script> -->\n");
      out.write("\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<title>Homepage</title>\n");
      out.write(" <script type=\"text/javascript\" src=\"javaScript/branchDetails.js\"></script>\n");
      out.write("<link href=\"cssFolder/homepages.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> \n");
      out.write("   <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script> \n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script> \n");
      out.write("  \n");
      out.write("  <style type=\"text/css\">\n");
      out.write("  \t#card{\n");
      out.write("\t\t \ttop:35px;\n");
      out.write("\t\t    align:\"center\";\n");
      out.write("\t\t    \n");
      out.write("\t\t    width: 400px;\n");
      out.write("\t\t    height: 200px;\n");
      out.write("\t\t    font-size: 15px;\n");
      out.write("\t\t    }\n");
      out.write("  \n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("<script type=\"text/javascript\">\n");
      out.write(" \n");
      out.write("function validateForm() {\n");
      out.write("\n");
      out.write("\t\tvar uname=document.forms[\"student\"][\"stname\"].value;\n");
      out.write("\t\tvar nameformat=/^[A-z]+$/;\n");
      out.write("\t\tvar email=document.forms[\"student\"][\"mail\"].value;\n");
      out.write("\t\tvar moblile=document.forms[\"student\"][\"mob\"].value;\n");
      out.write("\t\tvar phoneno = /^((\\+)?(\\d{2}[-]))?(\\d{10}){1}?$/;\n");
      out.write("\t\tvar mailformat = /^\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$/; \n");
      out.write("\t\tvar emailValidation=/^\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,3}$/;\n");
      out.write("\t\tvar isValid=true;\n");
      out.write("\n");
      out.write("\t\tif(!nameformat.test(uname) )\n");
      out.write("\t\t {\n");
      out.write("\t\t\talert(\"please enter char only\");\n");
      out.write("\t\t\tisValid =false;\n");
      out.write("\t\t}\n");
      out.write("\t\tconsole.log(\"inside\");\n");
      out.write("\t\t if(!emailValidation.test(email))\n");
      out.write("\t\t{\n");
      out.write("\t\t\t\tconsole.log(\"email fails\");\n");
      out.write("\t\t\talert(\"wrong Email pattern\");\n");
      out.write("\t\t\tisValid =false;\n");
      out.write("\t\t}  \n");
      out.write("\t\t\n");
      out.write("\t\tif(!phoneno.test(moblile))\n");
      out.write("\t\t{\n");
      out.write("\t\t\talert(\"enter the valid mobile number\");\n");
      out.write("\t\t\tisValid= false;\n");
      out.write("\t\t}\n");
      out.write("\t if(isValid==false) {\n");
      out.write("\t\treturn false;\n");
      out.write("\t} \n");
      out.write("} \n");
      out.write(" \n");
      out.write("</script>\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");

response.setHeader("Cache-Control", "no-cache");
response.setHeader("Cache-Control", "no-store");
response.setHeader("Pragma", "no-cache");
response.setDateHeader("Expires", 0); 
String name = (String) session.getAttribute("name");

if(name==null || name=="")
{
	response.sendRedirect("Signin.jsp");
	/* session.invalidate(); */
}

 
      out.write("\n");
      out.write("\n");
      out.write("\t<nav class=\"navbar navbar-default\">\n");
      out.write("\t  <div class=\"container-fluid\" id=\"navbar\">\n");
      out.write("\t\t    <div class=\"navbar-header\">\n");
      out.write("\t\t      <h3>WELCOME</h3>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t    \n");
      out.write("\t\t    <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t      <li><a>");
      out.print(session.getAttribute("name"));
      out.write("</a></li>\n");
      out.write("\t\t       <li><a href=\"#\" align=\"right\"></a></li>\n");
      out.write("\t\t     \n");
      out.write("\t\t     <li><a href=\"LogOut\"><span class=\"glyphicon glyphicon-log-in\"></span> Logout</a></li> \n");
      out.write("\t\t      <li><a href=\"#\" align=\"right\"></a></li>\n");
      out.write("\t\t    </ul>\n");
      out.write("\t  </div>\n");
      out.write("\t</nav>\n");
      out.write("\t\n");
      out.write("\t<div class=\"headpre\" align=\"center\">\n");
      out.write("\t<h2>COLLEGE APP</h2>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"col-sm-1\"></div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"col-sm-3 vert\" id=\"ece\"   style=\"background-color:yellow;\">\n");
      out.write("\t\t\t  <div class=\"cont\" >\n");
      out.write("\t\t\t\t<h align=\"center\"><b>ECE</b></h><br><br>\n");
      out.write("\t\t\t\t<p style=\"font-style: italic;\">You can view the details of Students they are\n");
      out.write("\t\t\t\t present in the ECE Deportment<p><br>\n");
      out.write("\t\t\t\t<button type=\"button\" name=\"csbtn\" class=\"btn\" \n");
      out.write("\t\t\t\tonclick=\"displayBranch('ECE')\">View Detailes</button>\n");
      out.write("\t\t\t  </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-1\"></div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"col-sm-3\" id=\"ece\" style=\"background-color:pink;\">\n");
      out.write("\t\t\t\t<h align=\"center\"><b>IT</b></h><br><br>\n");
      out.write("\t\t\t\t<p style=\"font-style: italic;\">You can view the details of Students they are\n");
      out.write("\t\t\t\t present in the IT Deportment<p><br>\n");
      out.write("\t\t\t\t<button type=\"button\" name=\"csbtn\" class=\"btn\"\n");
      out.write("\t\t\t\tonclick=\"displayBranch('IT')\">View Detailes</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-1\"></div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t <div class=\"col-sm-3\" id=\"ece\"  style=\"background-color:yellow;\">\n");
      out.write("\t\t\t\t<h align=\"center\"><b>COMP</b></h><br><br>\n");
      out.write("\t\t\t\t<p style=\"font-style: italic;\">You can view the details of Students they are\n");
      out.write("\t\t\t\t present in the COMP Deportment<p><br>\n");
      out.write("\t\t\t\t<button type=\"button\" name=\"csbtn\" class=\"btn\" \n");
      out.write("\t\t\t\tonclick=\"displayBranch('CSE')\">View Detailes</button>\n");
      out.write("\t\t\t</div>  \n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t<br><br><br><br><br><br>\n");
      out.write("\t\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t<div class=\"col-sm-9\"></div>\n");
      out.write("\t<div class=\"col-sm-1\">\n");
      out.write("\t<!-- Trigger the modal with a button -->\n");
      out.write("  <button type=\"button\" class=\"btn btn-info btn-lg\" id=\"addbtns\" data-toggle=\"modal\" data-target=\"#myModal\">\n");
      out.write("  Add</button>\n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("\n");
      out.write("  <!-- add Modal -->\n");
      out.write("  <div class=\"modal fade\"  id=\"myModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("    \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("          <h4 class=\"modal-title\">Add new Student</h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("         \t\n");
      out.write("         \t<div class=\"addtable\" align=\"center\">\n");
      out.write("    \t<!-- \n");
      out.write("    \t<h3>Add new Student </h3>\n");
      out.write("    \t -->\n");
      out.write("    \t \n");
      out.write("    \t \t\t\t<form class=\"form-horizontal\" action=\"newStudent\" method=\"post\" name=\"student\" onsubmit=\"return validateForm()\" >\n");
      out.write("    \t \t\t\t\t\t <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"name\">Name:</label>\n");
      out.write("\t\t\t\t\t\t\t      <div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t      \t<!-- <div class=\"form-control\"> -->\n");
      out.write("\t\t\t\t\t\t\t        <input type=\"text\" name=\"stname\" placeholder=\"Enter the name\" required>\n");
      out.write("\t\t\t\t\t\t\t        <!-- </div> -->\n");
      out.write("\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t   </div>\n");
      out.write("\t\t\t\t\t\t   \n");
      out.write("\t\t\t\t\t\t    <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"mobile\">Mobile:</label>\n");
      out.write("\t\t\t\t\t\t\t      <div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t      \t<!-- <div class=\"form-control\"> -->\n");
      out.write("\t\t\t\t\t\t\t        <input type=\"text\" name=\"mob\" placeholder=\"XXXXXXXXXX\"  required>\n");
      out.write("\t\t\t\t\t\t\t        <!-- </div> -->\n");
      out.write("\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t   </div>\n");
      out.write("\t\t\t\t\t\t   \n");
      out.write("\t\t\t\t\t\t   <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"email\">Email:</label>\n");
      out.write("\t\t\t\t\t\t\t      <div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t      \t\t<!-- <div class=\"form-control\"> -->\n");
      out.write("\t\t\t\t\t\t\t        <input type=\"text\" name=\"mail\" placeholder=\"ex-email@gmail.com\"\n");
      out.write("\t\t    \t\t\t\t\t\t\t\trequired>\n");
      out.write("\t\t    \t\t\t\t\t\t\t<!-- \t</div> -->\n");
      out.write("\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t   </div>\n");
      out.write("\t\t\t\t\t\t   \n");
      out.write("\t\t\t\t\t\t   <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"stream\">Stream:</label>\n");
      out.write("\t\t\t\t\t\t\t      <div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t       \t\t <select name=\"stream\" class=\"form-control\" placeholder=\"select\">\n");
      out.write("\t\t\t\t\t\t\t\t    \t\t\t<option value=\"ECE\">ECE</option>\n");
      out.write("\t\t\t\t\t\t\t\t    \t\t\t<option value=\"IT\">IT</option>\n");
      out.write("\t\t\t\t\t\t\t\t    \t\t\t<option value=\"CSE\">Comp</option>\n");
      out.write("\t\t\t\t\t\t\t\t    \t\t</select>\n");
      out.write("\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t   </div>\n");
      out.write("\t\t\t\t\t\t   \n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\t   \n");
      out.write("\t\t    \t\t<button type=\"button\" class=\"btn btn-default\" id=\"cls\" data-dismiss=\"modal\" style=\"align=right\">Close</button>\n");
      out.write("         \n");
      out.write("\t    \t\t\t<!-- <input type=\"submit\" value=\"Add\"> -->\n");
      out.write("\t    \t\t\t<button type=\"submit\" class=\"btn btn-default\" id=\"addbtn\" style=\"background: green\" style=\"width=2px\">Save</button>\n");
      out.write("\t    \t\t</div>\n");
      out.write("\t    \t</form> \n");
      out.write("         \t\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write(" \n");
      out.write("  \n");
      out.write("  \t\t\t\n");
      out.write("\t\t\t\t <!-- display the studentlist Modal -->\n");
      out.write("\t\t\t\t  <div class=\"modal fade\" id=\"myModal1\" role=\"dialog\">\n");
      out.write("\t\t\t\t    <div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t    \n");
      out.write("\t\t\t\t      <div class=\"modal-content\" id=\"abc\">\n");
      out.write("\t\t\t\t        <div class=\"modal-header\"  id=\"branch-title\">\n");
      out.write("\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\t\t\t\t          <h4 class=\"modal-title\"></h4>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t\t        <div class=\"modal-body\" id=\"tablecnt\">\n");
      out.write("\t\t\t\t          <p></p>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t\t        <div class=\"modal-footer\">\n");
      out.write("\t\t\t\t          <!-- <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button> -->\n");
      out.write("\t\t\t\t           <button type=\"button\" id=\"cls1\" class=\"btn btn-default\" data-dismiss=\"modal\" style=\"align:right\">Close</button>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t      \n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t <!--  <h2>Modal Example</h2>\n");
      out.write("\t\t\t  Trigger the modal with a button\n");
      out.write("\t\t\t  <button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">Open Modal</button> -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t  <!-- Editing Modal -->\n");
      out.write("\t\t\t  <div class=\"modal fade\" id=\"editModal\" role=\"dialog\">\n");
      out.write("\t\t\t    <div class=\"modal-dialog\">\n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t   <!--  <form class=\"form-horizontal\" action=\"EditedData\" method=\"post\"> -->\n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t      <!-- Modal content-->\n");
      out.write("\t\t\t      <div class=\"modal-content2\">\n");
      out.write("\t\t\t        <div class=\"modal-header\">\n");
      out.write("\t\t\t         \n");
      out.write("\t\t\t          <h4 class=\"modal-title\">Edit student details</h4>\n");
      out.write("\t\t\t        </div>\n");
      out.write("\t\t\t        <div class=\"modal-body\">\n");
      out.write("\t\t\t         <!--  <p>Some text in the modal.</p> -->\n");
      out.write("\t\t\t         \t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"name\">S-id:</label>\n");
      out.write("\t\t\t\t\t\t      <div class=\"col-sm-5\">\n");
      out.write("\t\t\t\t\t\t        <input type=\"text\" id=\"sidEdit\" name=\"sid\" disabled=\"disabled\"> \n");
      out.write("\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t   </div><br>\n");
      out.write("\t\t\t         \n");
      out.write("\t\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"name\">Name:</label>\n");
      out.write("\t\t\t\t\t\t      <div class=\"col-sm-5\">\n");
      out.write("\t\t\t\t\t\t        <input type=\"text\" id=\"nameEdit\" name=\"stname\"> \n");
      out.write("\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t   </div><br>\n");
      out.write("\t\t\t\t          \n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t\t\t\t         <!--  <div class=\"row\">\n");
      out.write("\t\t\t\t\t\t          <div class=\"col-sm-1\"></div>\n");
      out.write("\t\t\t\t\t\t          <div class=\"col-sm-3\" align=\"right\">Name:</div>\n");
      out.write("\t\t\t\t\t\t          <div class=\"col-sm-5\" id=\"nameEdit\"><input type=\"text\" name=\"stname\" required></div>\n");
      out.write("\t\t\t\t\t\t          <div class=\"col-sm-3\"></div>\n");
      out.write("\t\t\t\t\t\t          </div> -->\n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t           <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"mobile\">Mobile_No:</label>\n");
      out.write("\t\t\t\t\t      <div class=\"col-sm-5\">\n");
      out.write("\t\t\t\t\t        <input type=\"text\" name=\"mob\" id=\"mobEdit\" pattern=\"[0-9]{10,10}\">\n");
      out.write("\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t   </div><br>\n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"email\">Email:</label>\n");
      out.write("\t\t\t\t\t      <div class=\"col-sm-5\">\n");
      out.write("\t\t\t\t\t        <input type=\"text\" name=\"mail\" id=\"emailEdit\"\n");
      out.write("\t\t    \t\t\t\t\tpattern=\"[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,3}$\" required>\n");
      out.write("\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t   </div>\n");
      out.write("\t\t\t          <br>\n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t          <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t      <label class=\"control-label col-sm-3\" for=\"stream\">Stream:</label>\n");
      out.write("\t\t\t\t\t      <div class=\"col-sm-8\">\n");
      out.write("\t\t\t\t\t        <select name=\"stream\" id=\"branchEdit\" placeholder=\"select\">\n");
      out.write("\t\t\t\t\t\t\t\t    \t\t\t<option value=\"ECE\">ECE</option>\n");
      out.write("\t\t\t\t\t\t\t\t    \t\t\t<option value=\"IT\">IT</option>\n");
      out.write("\t\t\t\t\t\t\t\t    \t\t\t<option value=\"CSE\">Comp</option>\n");
      out.write("\t\t\t\t\t\t\t\t    \t\t\t</select>\n");
      out.write("\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t   </div>  \n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t            <!-- <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t     < <label class=\"control-label col-sm-3\" for=\"uid\">UID:</label>\n");
      out.write("\t\t\t\t\t      <div class=\"col-sm-5\">\n");
      out.write("\t\t\t\t\t        <input type=\"text\" name=\"usn\" required>\n");
      out.write("\t\t\t\t\t      </div> \n");
      out.write("\t\t\t\t\t   </div><br>   -->\n");
      out.write("\t\t\t             \n");
      out.write("\t\t\t       </div> \n");
      out.write("\t\t\t        \n");
      out.write("\t\t\t        <div class=\"modal-footer\">\n");
      out.write("\t\t\t        <button type=\"button\" class=\"btn btn-default\" id=\"cls\" data-dismiss=\"modal\" style=\"align=right\">Close</button>\n");
      out.write("\t\t\t         <!--  <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button> -->\n");
      out.write("\t\t\t          <button type=\"submit\" class=\"btn btn-default\" id=\"addbtn\"\n");
      out.write("\t\t\t           style=\"background: green\" style=\"width:2px\" data-target=\"#editModal\" onclick=\"afterEdit()\" >Submit</button>\n");
      out.write("\t\t\t        </div>\n");
      out.write("\t\t\t      \n");
      out.write("\t\t\t      \n");
      out.write("\t\t\t      </div> \n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t  </div>\n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
