/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-10-31 06:19:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Registration</title>\n");
      out.write("\n");
      out.write("<link href=\"cssFolder/reg.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"register.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"javaScript/passwordmatch.js\"></script>\n");
      out.write(" \n");
      out.write("</head>\n");
      out.write("<body >\n");
      out.write("<div align=\"center\">\n");
      out.write("\n");
      out.write("\t<form name=\"reg\" action=\"Read\" method=\"post\" align=\"center\"  onsubmit=\"return validateForm()\" >\n");
      out.write("\t<div align=\"center\">\n");
      out.write("\t<fieldset align=\"center\">\n");
      out.write("\t\t<div align=\"left\">\n");
      out.write("\t\t\t<h3>Create an Account</h3>\n");
      out.write("\t\t\t<hr> </div>\n");
      out.write("\t\t<div align=\"left\" >\n");
      out.write("\t\t\tEnter your name<br /> \n");
      out.write("\t\t\t<input type=\"text\" name=\"name\" required><br /> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div align=\"left\">\n");
      out.write("\t\t\tEnter your email<br /> \n");
      out.write("\t\t\t<input type=\"text\" name=\"email\" \n");
      out.write("\t\t\t required><br /> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div align=\"left\">\n");
      out.write("\t\t\tEnter your password<br /> \n");
      out.write("\t\t\t<input type=\"password\" name=\"password\"  required title=\"6 to 12 characters\"><br /> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div align=\"left\">\n");
      out.write("\t\t\tConfirm password<br /> \n");
      out.write("\t\t\t<input type=\"password\" name=\"confirmpassword\"  required title=\"6 to 12 characters\"><br /> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div align=\"left\">\n");
      out.write("\t\t\tEnter User Mobile_Number<br /> \n");
      out.write("\t\t\t<input type=\"number\" name=\"mob\" required><br /> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<p class=\"dotted\"> By Clicking On The \"create an account\" bellow.\n");
      out.write("\t\tyou certify that you read have read and agree to our \n");
      out.write("\t\t \t<a href=\"#\">terms of use </a> and \n");
      out.write("\t\t \t<a href=\"#\">privacy policy </a>\n");
      out.write("\t\t </p>\n");
      out.write("\t\t\n");
      out.write("\t\t<div align=\"left\">\n");
      out.write("\t\t<button type=\"submit\">Create an account</button>\n");
      out.write("\n");
      out.write("\t\t<p>Create an account?<a href=\"Signin.jsp\">Sign in.</a></p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write(" \t\t</fieldset>\n");
      out.write("\t </div>\n");
      out.write("\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
