/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-10-31 06:19:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>LogIn page</title>\n");
      out.write(" <script type=\"text/javascript\" src=\"javaScript/forgetpassword.js\"></script>\n");
      out.write("<link href=\"cssFolder/login.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body >\n");
      out.write("\n");

response.setHeader("Cache-Control", "no-cache");
response.setHeader("Cache-Control", "no-store");
response.setHeader("Pragma", "no-cache");
response.setDateHeader("Expires", 0); 
String error = (String) session.getAttribute("error");

if(error!=null || error!="")
{
	error=null;

      out.write("\n");
      out.write("\n");
      out.write("\t<!-- <p>Email or Password wrong</p>  -->\n");
      out.write("\t\n");
      out.write("\t<!-- <script >\n");
      out.write("\talert(\"Email or Password wrong\");\n");
      out.write("\t</script> --> \n");
}

 
      out.write("\n");
      out.write("\n");
      out.write("<!-- <div class=\"container\"> -->\n");
      out.write("\t<!-- <form name=\"loginpage\" action=\"Verify\" method=\"post\"> -->\n");
      out.write("\t\t<div align=\"center\" >\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"row\" >\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\" style=\"background-color:  #00ffff\">\n");
      out.write("\t\t\t\t\t\t<h3 align=\"left\"><b>Sign In</b></h3>\n");
      out.write("\t\t\t\t\t\t<hr >\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6 vert\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 align=\"left\"><b>Use other account</b></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t<p align=\"left\" style=\"font-size:10\">You can also sign in using Facebook account and Google\n");
      out.write("\t\t\t\t\t\t\t\t\taccount</p>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"fbbutton\" onclick=\"#\">login using facebook</button>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"gbutton\">login using google</button>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<form name=\"loginpage\" action=\"Verify\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<h4 align=\"center\"><b>Using your account</b></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<br> <input type=\"text\" name=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"enter ur email\"> <br> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"Password\" placeholder=\"enter ur password\">\n");
      out.write("\t\t\t\t\t\t\t\t<br> <input type=\"submit\" value=\"Sign In\"> <br>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <a href=\"#\" align=\"left\">forgot password?</a><br> -->\n");
      out.write("\t\t\t\t\t\t\t\t<a data-toggle=\"modal\" data-target=\"#myModal\" style=\"align:'left'\">forgot password?    </a><br>\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"Register.jsp\">Register</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</form> \n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- </div> -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("    \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("          <h4 class=\"modal-title\">Forget Password</h4>\n");
      out.write("        </div>\n");
      out.write("        <!-- <form action=\"ForgetPW\" method=\"post\"> -->\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <p>Enter your email</P>\n");
      out.write("          <input type=\"text\" name=\"email\" id=\"email\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("        \n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("          <button type=\"submit\" class=\"btn btn-default\" onclick=\"forget()\" >submit</button>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("       <!--  </form> -->\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <!-- Modal -->\n");
      out.write("  <div class=\"modal fade\" id=\"myModal1\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("    \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("       \n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <p>your password .</p>\n");
      out.write("          \n");
      out.write("          <p ></p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\t\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
